name: vetroplach-firmware-rust

on:
  pull_request:
     paths:
      - "firmware/vetroplach/**"
      - '.github/workflows/vetroplach-firmware.yaml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware/vetroplach
    strategy:
      fail-fast: true
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check
          - command: clippy
            args: --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32s3
          # This needs to be compatible with flake.nix
          version: "1.88.0"
          ldproxy: false
          workdir: firmware/vetroplach
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
