name: vetroplach-board-gerbers

on:
  pull_request:
    paths:
    - 'vetroplach-board/*.kicad_sch'
    - 'vetroplach-board/*.kicad_pcb'
    - 'vetroplach-board/*.kibot.yaml'
    - '.github/workflows/vetroplach-board.yaml'
  workflow_dispatch:
    inputs:
      name:
        description: 'Workflow run name'
        required: false
        default: 'vetroplach-board gerbers'
  
jobs:
  jlcpcb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        config: jlcpcb.kibot.yaml
        dir: output
        schema: 'vetroplach-board/vetroplach-board.kicad_sch'
        board: 'vetroplach-board/vetroplach-board.kicad_pcb'
    - name: 'Cleanup build folder'
      run: sudo rm -rf ./output/tmp
    - name: 'Upload results'
      uses: actions/upload-artifact@v4
      with:
        name: vetroplach-board-jlcpcb
        path: output
